version: "3.8"

services:
  server:
    build: .
    network_mode: "host"
    volumes:
      - .:/app
    depends_on:
      - database
    env_file:
      - .env_server

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: pgdbpass
      POSTGRES_USER: pgdbuser
    ports:
      - "5432:5432"
    restart: always

